package com.elezeta.roguecave.sprites;

public enum SpriteSlotID {

	BOOTS,
	LEGS, // #SHORTS
	HAIRDROPFRONT,
	HELMETFULL, //#HELMETHALF #HAIRLONG #BEARDLONG #HAIRDROPFRONT #HAIRDROPBACK
	HELMETHALF, // #HAIRLONG
	HAIRDROPBACK,
	HAIRLONG,
	BEARDLONG,
	RIGHTHANDFRONT,
	LEFTHANDFRONT,
	ARMSFRONT,
	ARMOR, //#TOP
	RIGHTHANDBACK,
	LEFTHANDBACK,
	ARMSBACK,
	AMULET,
	RINGLEFT, // filter
	RINGRIGHT, // filter
	HAIRSHORT,
	BEARDSHORT,
	EYEBROWS,
	EYECOLOR,
	EYEWHITE,
	EYESKIN,
	SHORTS,
	TOP,
	BODY
}
